### ISSUE TITLE
Preferences not loading

### ISSUE THREAD

**Issue by TheRealKeto** [guillermo-moran/iAppLocker#2]
For me, at least, the Preferences don't load. It only reports me with the error and tells me that the Preference Bundle couldn't be loaded. I don't know if this has to do with how you install the tweak or something so. 

Here's what I mean:
https://user-images.githubusercontent.com/24854941/36004915-1a2d44c0-0d03-11e8-8671-38bef4d7001b.png

**Comment by guillermo-moran** [comment]
This tweak no longer works. Feel free to update it tho :)

Sent from my iPhone

On Feb 8, 2018, at 6:06 PM, TheRealKeto <notifications@github.com<mailto:notifications@github.com>> wrote:


For me, at least, the Preferences don't load. It only reports me with the error and tells me that the Preference Bundle couldn't be loaded. I don't know if this has to do with how you install the tweak or something so.

Here's what I mean:
https://user-images.githubusercontent.com/24854941/36004915-1a2d44c0-0d03-11e8-8671-38bef4d7001b.png
